version: '2'
services:
  mongodb:
    image: mongo:latest
    restart: always
  iot-consumer:
    build:
      context: ./
      dockerfile: docker/consumer.Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker,
      SPRING_DATA_MONGODB_URI : mongodb://127.0.0.1:27017
  iot-api:
    build:
      context: ./
      dockerfile: docker/api.Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI : mongodb://127.0.0.1:27017
  iot-model:
    build:
      context: ./
      dockerfile: docker/model.Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
